### ISSUE TITLE
Breaking Bug In v2.0.1

### ISSUE THREAD

**Issue by mehulbaid** [es-shims/Promise.any#10] opened 2021-03-09 07:28 UTC
Using the code below (same used to work with 1.17.7), the promise.any is not working anymore.

node version: 12.10

```
const any = require('promise.any');

var p1 = new Promise((resolve, reject) => {setTimeout(resolve, 100, 'p1')})
var p2 = new Promise((resolve, reject) => {setTimeout(resolve, 200, 'p2')})
var p3 = new Promise((resolve, reject) => {setTimeout(resolve, 300, 'p3')})

var promises = [p1, p2, p3];
any(promises).then(res => console.log(res));
```
getting the following error.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/27810481/110433910-1dba3a80-80d7-11eb-8099-582cab6662d9.png">

**Comment by ljharb** [comment] 2021-03-09 18:48
However, I still can't reproduce the error on node v12.10 with any of the three published versions of `call-bind`.

I'm trying now with all the various versions of `es-abstract` to see if that can repro it.

**Comment by ljharb** [comment] 2021-03-09 18:50
No luck.

If upgrading (by reinstalling `promise.any`) doesn't solve it, and if I can reproduce it, I'll be happy to fix it - could you perhaps share the `demo` repo this is happening in?

**Comment by codetheweb** [comment] 2021-03-09 23:26
I also just recently started [seeing reports of the same issue](https://github.com/codetheweb/tuyapi/issues/432).

My guess is that a resolved version changed somewhere (like you said) but I'm not sure what it is.

[Here's a repo](https://github.com/codetheweb/promise.any-reproduce) that reproduces the issue (if you can't reproduce it using your system Node.js install, try the Dockerfile).

**Comment by ljharb** [comment] 2021-03-09 23:32
Thanks; I've reproduced it. I'll see what I can do.

**Comment by mehulbaid** [comment] 2021-03-09 23:39
Sure @ljharb.

**Comment by ljharb** [comment] 2021-03-09 23:45
Fixed in 996c30b; v2.0.2 is published.

**Closed by ljharb** 2021-03-09 23:45 UTC

**Comment by codetheweb** [comment] 2021-03-09 23:54
Looks like it's working now; thank you so much!

**Comment by mehulbaid** [comment] 2021-03-09 23:56
Thanks a lot @codetheweb and @ljharb for the quickest resolution

**Comment by ljharb** [comment] 2021-03-09 23:56
Thank you for the repro case, and sorry for the inconvenience.

**Comment by mehulbaid** [comment] 2021-03-09 23:57
@ljharb , No worries happens with the best of us.
